import { AssessmentQuestion } from './types';

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // ── Dimension 1: Interests (Q1–Q7) ──
  {
    id: 1,
    dimension: 'interests',
    text: 'Which domain of technology excites you the most?',
    type: 'single_choice',
    options: [
      { id: 'swe', label: 'Building complex software architectures, application backends, and systems', value: 1 },
      { id: 'ds', label: 'Extracting patterns from vast datasets, analytics, and business insights', value: 2 },
      { id: 'web', label: 'Crafting responsive, visual, and highly interactive user interfaces on the web', value: 3 },
      { id: 'cyber', label: 'Securing networks, auditing systems for safety, and ethical hacking', value: 4 },
      { id: 'cloud', label: 'Designing scalable infrastructure, virtualization, and distributed systems', value: 5 },
      { id: 'mobile', label: 'Developing native and cross-platform applications for smartphones and tablets', value: 6 },
      { id: 'devops', label: 'Automating deployment pipelines, continuous integration, and infrastructure management', value: 7 },
      { id: 'aiml', label: 'Training neural networks, building intelligent agents, and cognitive computing', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },
  {
    id: 2,
    dimension: 'interests',
    text: 'What kind of problems do you enjoy solving the most?',
    type: 'single_choice',
    options: [
      { id: 'logical', label: 'Algorithmic and logical problems (e.g., designing efficient algorithms)', value: 1 },
      { id: 'analytical', label: 'Data-driven and statistical problems (e.g., finding hidden insights in data)', value: 2 },
      { id: 'creative', label: 'Visual and user-centric problems (e.g., building intuitive UX/UI)', value: 3 },
      { id: 'systemic', label: 'Operational and systemic problems (e.g., system configuration, security, automation)', value: 4 },
    ],
    careerMapping: {
      'Software Development': 4,
      'Data Science': 4,
      'Web Development': 4,
      'Cybersecurity': 4,
      'Cloud Computing': 4,
      'Mobile App Development': 4,
      'DevOps': 4,
      'AI/ML Engineering': 4,
    },
  },
  {
    id: 3,
    dimension: 'interests',
    text: 'Which tech topic would you spend a weekend learning about?',
    type: 'single_choice',
    options: [
      { id: 'clean_code', label: 'Design patterns, refactoring, and clean code principles', value: 1 },
      { id: 'pandas_numpy', label: 'Statistical modeling, database queries, and predictive analysis', value: 2 },
      { id: 'frontend_frameworks', label: 'Modern UI frameworks (Next.js, Vue, Tailwind CSS)', value: 3 },
      { id: 'ctf_hacking', label: 'Cryptography, network defense, and Capture-the-Flag challenges', value: 4 },
      { id: 'aws_services', label: 'Cloud architectures, serverless computing, and AWS/Azure resources', value: 5 },
      { id: 'swift_kotlin', label: 'iOS/Android SDKs, mobile gestures, and app store publishing', value: 6 },
      { id: 'ci_cd', label: 'CI/CD automation, Docker containers, and Kubernetes orchestration', value: 7 },
      { id: 'pytorch_llms', label: 'Deep learning frameworks, neural networks, and prompt engineering', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },
  {
    id: 4,
    dimension: 'interests',
    text: 'What type of projects interest you the most?',
    type: 'single_choice',
    options: [
      { id: 'proj_api', label: 'Developing a REST/GraphQL API for an e-commerce backend', value: 1 },
      { id: 'proj_eda', label: 'Analyzing global temperature trends using datasets and Jupyter Notebooks', value: 2 },
      { id: 'proj_web', label: 'Creating an interactive, animated portfolio website or dashboard', value: 3 },
      { id: 'proj_sec', label: 'Setting up a secure firewall and penetration testing a network', value: 4 },
      { id: 'proj_cloud', label: 'Deploying a high-availability server setup using cloud infrastructure', value: 5 },
      { id: 'proj_mob', label: 'Building a cross-platform mobile task management or social app', value: 6 },
      { id: 'proj_pipeline', label: 'Writing scripts to build and deploy docker containers on git commits', value: 7 },
      { id: 'proj_nn', label: 'Training an image classifier or fine-tuning a small language model', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },
  {
    id: 5,
    dimension: 'interests',
    text: 'Which tech trend excites you the most?',
    type: 'single_choice',
    options: [
      { id: 'trend_saas', label: 'SaaS architectures, microservices, and web APIs', value: 1 },
      { id: 'trend_bigdata', label: 'Big Data analysis, warehouse technologies (Snowflake, Spark)', value: 2 },
      { id: 'trend_web3', label: 'Web3, interactive interfaces, dynamic frontends', value: 3 },
      { id: 'trend_zero_trust', label: 'Zero-trust architecture and cybersecurity threats mitigation', value: 4 },
      { id: 'trend_edge', label: 'Serverless, edge computing, and distributed cloud virtualization', value: 5 },
      { id: 'trend_wearables', label: 'Wearable tech, mobile applications, IoT interfaces', value: 6 },
      { id: 'trend_gitops', label: 'GitOps, Infrastructure as Code, automation scripts', value: 7 },
      { id: 'trend_generative_ai', label: 'Generative AI, Large Language Models, autonomous systems', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },
  {
    id: 6,
    dimension: 'interests',
    text: 'What kind of impact do you want to make in your career?',
    type: 'single_choice',
    options: [
      { id: 'imp_robust', label: 'Building robust, core systems that support millions of transactions', value: 1 },
      { id: 'imp_data', label: 'Guiding critical business decisions through data and logic', value: 2 },
      { id: 'imp_ux', label: 'Creating products that look stunning and feel incredibly natural to use', value: 3 },
      { id: 'imp_protect', label: 'Protecting vital infrastructure and securing user privacy', value: 4 },
      { id: 'imp_scale', label: 'Enabling companies to scale rapidly on global, virtual platforms', value: 5 },
      { id: 'imp_pocket', label: 'Delivering useful and engaging software straight to users\' pockets', value: 6 },
      { id: 'imp_delivery', label: 'Speeding up software releases and ensuring continuous stability', value: 7 },
      { id: 'imp_intel', label: 'Adding human-like intelligence and decision making to software', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },
  {
    id: 7,
    dimension: 'interests',
    text: 'Which role model career inspires you the most?',
    type: 'single_choice',
    options: [
      { id: 'rm_swe', label: 'Principal Software Architect (designing systems at Uber/Netflix)', value: 1 },
      { id: 'rm_ds', label: 'Chief Data Scientist (analysing user graphs at Meta)', value: 2 },
      { id: 'rm_web', label: 'Creative Tech Director (designing experiences at Apple/Stripe)', value: 3 },
      { id: 'rm_cyber', label: 'Security Researcher / Ethical Hacker (finding vulnerabilities)', value: 4 },
      { id: 'rm_cloud', label: 'Cloud Infrastructure Architect (managing AWS/GCP services)', value: 5 },
      { id: 'rm_mob', label: 'Mobile Product Developer (launching trending App Store apps)', value: 6 },
      { id: 'rm_devops', label: 'Reliability Engineer (managing deployments at scale)', value: 7 },
      { id: 'rm_aiml', label: 'AI/ML Research Scientist (creating GPT or AlphaGo models)', value: 8 },
    ],
    careerMapping: {
      'Software Development': 5,
      'Data Science': 5,
      'Web Development': 5,
      'Cybersecurity': 5,
      'Cloud Computing': 5,
      'Mobile App Development': 5,
      'DevOps': 5,
      'AI/ML Engineering': 5,
    },
  },

  // ── Dimension 2: Skills (Q8–Q14) ──
  {
    id: 8,
    dimension: 'skills',
    text: 'Rate your proficiency in Python programming.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Data Science': 5,
      'AI/ML Engineering': 5,
      'DevOps': 3,
      'Software Development': 3,
    },
  },
  {
    id: 9,
    dimension: 'skills',
    text: 'Rate your proficiency in Frontend Web Technologies (HTML, CSS, JavaScript, React).',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Web Development': 5,
      'Mobile App Development': 3,
      'Software Development': 2,
    },
  },
  {
    id: 10,
    dimension: 'skills',
    text: 'Rate your proficiency in databases and SQL/NoSQL querying.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Software Development': 4,
      'Data Science': 4,
      'Web Development': 3,
      'DevOps': 3,
      'AI/ML Engineering': 2,
    },
  },
  {
    id: 11,
    dimension: 'skills',
    text: 'Rate your proficiency in System Design and Architecture.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Software Development': 5,
      'Cloud Computing': 5,
      'DevOps': 4,
      'Mobile App Development': 3,
    },
  },
  {
    id: 12,
    dimension: 'skills',
    text: 'Rate your proficiency in Computer Networks and Security protocols.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Cybersecurity': 5,
      'Cloud Computing': 4,
      'DevOps': 3,
    },
  },
  {
    id: 13,
    dimension: 'skills',
    text: 'Rate your proficiency in Mobile App Development (React Native, Flutter, Native Swift/Kotlin).',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'Mobile App Development': 5,
      'Web Development': 2,
    },
  },
  {
    id: 14,
    dimension: 'skills',
    text: 'Rate your proficiency in Linux command line interface (CLI) and Shell scripting.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    careerMapping: {
      'DevOps': 5,
      'Cloud Computing': 4,
      'Cybersecurity': 4,
      'Software Development': 2,
    },
  },

  // ── Dimension 3: Work Style (Q15–Q20) ──
  {
    id: 15,
    dimension: 'work_style',
    text: 'Do you prefer working alone on deep logic, or collaborating closely in cross-functional teams?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Independent deep dive',
    maxLabel: 'Collaborative team play',
    careerMapping: {
      'Web Development': 4,
      'Mobile App Development': 4,
      'Software Development': 3,
      'DevOps': 3,
      'Data Science': 3,
      'Cybersecurity': 2,
      'AI/ML Engineering': 2,
      'Cloud Computing': 2,
    },
  },
  {
    id: 16,
    dimension: 'work_style',
    text: 'How do you handle deadlines and pacing?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Meticulous & methodical (no rush)',
    maxLabel: 'Fast-paced & deadline-driven',
    careerMapping: {
      'DevOps': 5,
      'Web Development': 4,
      'Mobile App Development': 4,
      'Software Development': 3,
      'Cybersecurity': 3,
      'Data Science': 2,
      'AI/ML Engineering': 2,
      'Cloud Computing': 2,
    },
  },
  {
    id: 17,
    dimension: 'work_style',
    text: 'What is your preferred style of learning new technologies?',
    type: 'single_choice',
    options: [
      { id: 'self_paced', label: 'Self-paced experimentation and reading documentation', value: 1 },
      { id: 'structured', label: 'Structured academic courses and certifications', value: 2 },
      { id: 'hands_on', label: 'Building hands-on projects and tutorials', value: 3 },
      { id: 'peer', label: 'Collaborative learning and peer coding sessions', value: 4 },
    ],
    careerMapping: {
      'Software Development': 4,
      'Data Science': 4,
      'Web Development': 4,
      'Cybersecurity': 4,
      'Cloud Computing': 4,
      'Mobile App Development': 4,
      'DevOps': 4,
      'AI/ML Engineering': 4,
    },
  },
  {
    id: 18,
    dimension: 'work_style',
    text: 'What is your communication preference for complex problems?',
    type: 'single_choice',
    options: [
      { id: 'async', label: 'Asynchronous text and written tickets (Slack, Jira)', value: 1 },
      { id: 'verbal', label: 'Real-time meetings and verbal explanations', value: 2 },
      { id: 'visual', label: 'Visual layouts, wireframes, and diagrams', value: 3 },
      { id: 'docs', label: 'Writing detailed design documents and code comments', value: 4 },
    ],
    careerMapping: {
      'Software Development': 3,
      'Data Science': 3,
      'Web Development': 4,
      'Cybersecurity': 3,
      'Cloud Computing': 3,
      'Mobile App Development': 4,
      'DevOps': 3,
      'AI/ML Engineering': 3,
    },
  },
  {
    id: 19,
    dimension: 'work_style',
    text: 'What type of project scope do you thrive in?',
    type: 'single_choice',
    options: [
      { id: 'deep_dive', label: 'Focused, deep-dive work on a single feature', value: 1 },
      { id: 'broad_var', label: 'Broad variety of tasks spanning different parts of the system', value: 2 },
      { id: 'ownership', label: 'End-to-end ownership of the entire lifecycle', value: 3 },
      { id: 'research', label: 'Experimental, research-oriented, and open-ended problems', value: 4 },
    ],
    careerMapping: {
      'Software Development': 4,
      'Data Science': 4,
      'Web Development': 4,
      'Cybersecurity': 4,
      'Cloud Computing': 4,
      'Mobile App Development': 4,
      'DevOps': 4,
      'AI/ML Engineering': 4,
    },
  },
  {
    id: 20,
    dimension: 'work_style',
    text: 'How important is innovation/cutting-edge tech versus stability/well-documented standards?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Stable & Proven (Enterprise Standards)',
    maxLabel: 'Cutting-Edge & Novel (AI, Startups)',
    careerMapping: {
      'AI/ML Engineering': 5,
      'Software Development': 4,
      'Mobile App Development': 4,
      'Web Development': 4,
      'Cloud Computing': 3,
      'DevOps': 3,
      'Data Science': 3,
      'Cybersecurity': 2,
    },
  },

  // ── Dimension 4: Values (Q21–Q25) ──
  {
    id: 21,
    dimension: 'values',
    text: 'How important is work-life balance and predictable hours to you?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Low priority (willing to work overtime)',
    maxLabel: 'Extremely high priority',
    careerMapping: {
      'Web Development': 4,
      'Data Science': 4,
      'Software Development': 3,
      'Mobile App Development': 3,
      'AI/ML Engineering': 3,
      'Cloud Computing': 3,
      'Cybersecurity': 2,
      'DevOps': 2, // DevOps has pager duty frequently
    },
  },
  {
    id: 22,
    dimension: 'values',
    text: 'Does the social/real-world impact of your products drive you?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Not a primary driver',
    maxLabel: 'Essential motivator',
    careerMapping: {
      'AI/ML Engineering': 4,
      'Mobile App Development': 4,
      'Web Development': 4,
      'Software Development': 3,
      'Data Science': 3,
      'Cybersecurity': 3,
      'Cloud Computing': 3,
      'DevOps': 3,
    },
  },
  {
    id: 23,
    dimension: 'values',
    text: 'Rank your priority: High Salary vs. Rapid Career Growth potential.',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Salary first',
    maxLabel: 'Growth first',
    careerMapping: {
      'AI/ML Engineering': 4,
      'Software Development': 4,
      'DevOps': 4,
      'Cloud Computing': 4,
      'Cybersecurity': 4,
      'Data Science': 4,
      'Web Development': 3,
      'Mobile App Development': 3,
    },
  },
  {
    id: 24,
    dimension: 'values',
    text: 'What size/type of organization do you prefer to join?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Large multinational corporation',
    maxLabel: 'Early-stage startup',
    careerMapping: {
      'Web Development': 4,
      'Mobile App Development': 4,
      'Software Development': 3,
      'AI/ML Engineering': 3,
      'DevOps': 3,
      'Data Science': 2,
      'Cloud Computing': 2,
      'Cybersecurity': 2, // Large companies focus more on security
    },
  },
  {
    id: 25,
    dimension: 'values',
    text: 'How critical is continuous learning and skill adaptation in your career?',
    type: 'slider',
    min: 1,
    max: 5,
    minLabel: 'Comfortable with stable skillset',
    maxLabel: 'Thrive on learning new tools weekly',
    careerMapping: {
      'AI/ML Engineering': 5,
      'DevOps': 5,
      'Cloud Computing': 5,
      'Software Development': 4,
      'Cybersecurity': 4,
      'Mobile App Development': 4,
      'Web Development': 4,
      'Data Science': 4,
    },
  },
];
